### ISSUE TITLE
We cannot find a block on disk.... on chain reorganisation.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-old#7]
Chain Test 20180520

1. Create a node and run it to generate cash
2. Create a second node listing one as a peer.
3. Add two as a peer for one (separate bug they won't synch if you don't)
4. Create blocks on the chain by sending messages.
5. Stop one and send messages to self on two to create blocks
6. Stop two and start one and send messages in a loop to create blocks
> Both nodes have 5 blocks but block 5 is different on each

7. Restart one.
8. Restart two.
9. Send a transaction from one:
> Error

```
START TIME: 1526824853109
Adding block 6 -> 1c31bed6ffd40e0df48c696f3ad839a8917d631da1bf629e8463ca54a527a125 1526823527616
UPDATING LONGEST CHAIN: 2 new |||||| 0 old 1
validate longest chain...
 ... unwind old chain
 ... validate block inputs and other stuff
 ... validate block inputs and other stuff
 ... validate block inputs and other stuff
FAILED TO VALIDATE SLIP: 591adcde0eca885d4a4a17ca06646b8566d20edaa4e4f8710279d65e017a93ba00136
{
    "add": "2242wmfGQiVrg3oUvSsLaziSudFdo6999f1FwWuVUMuGR",
    "amt": 36,
    "gt": 0,
    "bid": 5,
    "tid": 9,
    "sid": 1,
    "bhash": "adcde0eca885d4a4a17ca06646b8566d20edaa4e4f8710279d65e017a93ba001",
    "lc": 1,
    "ft": 0,
    "rn": 63
}
MY GBID: 1
 ... unwind old chain
We cannot find a block on disk that should exist in unwindChain
```

> NB have tested in various combinations including creating one longer chain... which ever way - when a chain reorg is forced I get this error.

**Comment by trevelyan** [comment]
I also cannot replicate this. Did you run a clean ./compile before you started Node 1 and began this experiment? If you did not it is possible that this problem is being caused by old data in the database.

If it is possible to replicate this, it would be useful to check in the 

/lib/data/blocks 

directory to see whether the block in question is in fact saved on disk. If it is NOT saved in there, then it must have been received over the network for the blockchain to know that it exists and try to push it into a longest chain.

If it is saved on disk it is a strange problem. If it is not saved on disk, the problem will be in the storage.js file's "saveBlock" function, since that is the point in the code where we are supposed to write these puppies to long-term storage.

**Comment by arpee** [comment]
This appears to have been rectified by work on the registry module.
