### ISSUE TITLE
Iran-Iraq War awards extra VP

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#92]
This happens when Flower Power is in affect so I think it's just a thing of Flower Power giving its 2 VP twice

Look at the log here

![image](https://user-images.githubusercontent.com/54612963/67217477-c7b9f980-f3f2-11e9-9897-f64346096fb5.png)

Another Instance:

![image](https://user-images.githubusercontent.com/54612963/67217543-e4eec800-f3f2-11e9-831e-d531df53e164.png)

**Comment by trevelyan** [comment]
We've gone through a long back-and-forth with how to handle Flower Power.

Do we handle them in the cards themselves? Or do we handle it outside?

I've just removed all handling of Flower Power within the card events. So
the game engine is checking now. The next update should fix this. It would
be good to test that it actually works afterwards, since it will affect ALL
war cards.....

Should be live on the server the next time we recompile the code, which
will be... tonight?

Will close the bug report then.

Cheers,

--david

**Comment by trevelyan** [comment]
I believe this is now fixed. Please help keep an eye open for this to confirm, as there are several war cards and Flower Power is a tricky one to fix / code!
